# Use official Node.js image as the base image
FROM node:14-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy Nuxt.js project files to the container
COPY . .

# Build the Nuxt.js application
RUN npm run build

# Expose port 3000 and start the application
EXPOSE 3000
CMD ["npm", "start"]
